### ISSUE TITLE
can i find some way to add annotations into span?

### ISSUE THREAD

**Issue by ccl0326** [openzipkin/zipkin-reporter-java#33] opened 2017-02-24 04:06 UTC
In previous brave with collector, we'd has some tricky interface likes reportSpans can modifiy or add custom annotations into span. But now we can not find any interfaces likes this, or i need to implement the new reporter.

**Comment by adriancole** [comment] 2017-02-27 04:56
can you give an example of what these would be? Are they
context-independent?

**Comment by ccl0326** [comment] 2017-02-28 01:38
@adriancole yep, they are context-independent. 
e.g. in microservice with docker i need to fill service name and instance no. into annotations to help us retrieval in zipkin UI.

**Comment by adriancole** [comment] 2017-02-28 01:48
neat idea having this in reporter. This would allow sharing for "platform
tags"

**Comment by ccl0326** [comment] 2017-02-28 01:58
@adriancole  i agree with this.

**Comment by llinder** [comment] 2017-02-28 02:10
We have the same need to add platform based tags as well.  I never had the thought about this living in the Reporter but that does seems like a good approach.

**Comment by adriancole** [comment] 2017-02-28 02:25
main impact is that the reporter doesn't create spans. In fact, it doesn't
even know the type of the span :(

we could have AsyncReporter accept a `Map<String, String>` of default tags.
We'd have to do funny math or special-case the size impact (otherwise, we'd
have to recreate the span on entry, like span.toBuilder().tag...build())..
the problem is that we don't have the type of the span to even know if it
has a builder. so implementation is a bit more straightforward doing this
in the tracer (recorder) directly.

only think straightforward way I can think of in this codebase is a custom
Encoder. There's api impact as Encoding is currently an enum, and Encoding
is the thing that calculates size. so, the choice is to break api (it is
<1.0 many don't use Encoding anyway, and you don't really break api much by
widening an enum to an interface or abstract class w/constants..), or live
with the slightly off size logic.

The custom Encoder itself would be relatively straightforward, as it can
change the spans.

All that said.. yeah most straightforward would be to handle this in the
tracer until such time as we add a "recorder" component here, which would
be able to instantiate span builders.

Thoughts?

**Comment by llinder** [comment] 2017-02-28 02:49
That makes sense.  My gut feeling was that adding tags here wouldn't be very straightforward.

Adding default tags to the Tracer seems a lot more natural to me.  For example:
```java
tracer = Tracer.newBuilder()
  .localServiceName("my-service")
  .defaultTags(Arrays.asList(
    Tag("region", theAwsRegion),
    Tag("environment", "dev") 
  ))
  .reporter(reporter)
  .build();
```

**Comment by ccl0326** [comment] 2017-02-28 03:30
@adriancole yes, i know that. i think only producer likes brave can modifiy the spans is better. but all the middlewares or implementations only covered the annotations they need. so i think maybe we can only do it here.

**Comment by adriancole** [comment] 2017-02-28 03:44
>
> @adriancole <https://github.com/adriancole> yes, i know that. i think
> only producer likes brave can modifiy the spans is better. but all the
> middlewares or implementations only covered the annotations they need. so i
> think maybe we can only do it here.
>
right, just practically speaking it is awkward here until/unless we add a
recorder functionality due to issues mentioned. What other tracers are you
using?

**Comment by ccl0326** [comment] 2017-02-28 04:00
@adriancole we just use brave and a self implementation with golang. we don't worry about this currently. but i think it's should be supported in future no matter in tracer or reporter.

**Comment by adriancole** [comment] 2017-02-28 04:33
looking at the implementation, it isn't practical to change the internals to do this. Encoding is an internal detail, and the encoder is custom per-sender.

The only option I can think of at this level of abstraction could be a reporter wrapper.

ex.
```java
class DefaultTagsReporter implements Reporter<Span> {
  Reporter<Span> delegate;
  Endpoint localEndpoint; // another problem with this abstraction vs Recorder or tracer itself!!

  @Override pubic void report(Span span) {
    Span withTags = span.toBuilder()
      .addBinaryAnnotation(BinaryAnnotation.create("foo", "bar", localEndpoint)
      .build();
    delegate.report(span);
  }
}
```

Basically, it isn't a good fit until/unless there's a Recorder component here (which would have a local endpoint etc). In the mean time, you can create something like above which can coordinate this. I've also created an issue in brave for this https://github.com/openzipkin/brave/issues/357

zipkin-reporter has highly reused code, so once we get more requests for this type of feature, we can revisit the topic. Until then, I'm closing the issue as a work-around exists and we've opened an issue in Brave. If you are using other tracers, please reference this issue when created related issues!

**Closed by adriancole** 2017-02-28 04:33 UTC

**Comment by adriancole** [comment] 2017-02-28 05:19
thanks for the feedback! read "close" as not yet. we'll keep an eye out

**Comment by adriancole** [comment] 2018-12-11 07:05
In https://github.com/openzipkin/brave/pull/801 show how to do this, especially only once per-hop:

```java
/**
 * This shows how you can add a tag once per span as it enters a process. This is helpful for
 * environment details that are not request-specific, such as region.
 */
public class DefaultTagsTest {
  List<zipkin2.Span> spans = new ArrayList<>();
  Tracing tracing = Tracing.newBuilder()
      .addFinishedSpanHandler(new FinishedSpanHandler() {
        @Override public boolean handle(TraceContext context, MutableSpan span) {
          if (context.isLocalRoot()) {
            // pretend these are sourced from the environment
            span.tag("env", "prod");
            span.tag("region", "east");
          }
          return true;
        }
      })
--snip--
```
