### ISSUE TITLE
Question regarding flushing

### ISSUE THREAD

**Issue by toaler** [openzipkin/zipkin-reporter-java#27] opened 2016-11-11 09:59 UTC
I've written a test program that creates a parent span and child span corresponding to the ID's bd7a977555f6b982 , ebf33e1a81dc6f71 respectively.  If I don't put a explicit flush between reporter.report(span), only the last span is written.  Is this by design?

https://gist.github.com/adriancole/e8823c19dfed64e2eb71

**Comment by adriancole** [comment] 2016-11-12 03:07
no coordination is needed when reporting spans (by design). That said all
spans should be reported.

In other words, when a span is complete, reporter.report(span) should be
called. The default behavior of AsyncReporter should be fine, waiting up to
a second or a size threshold before sending to zipkin. This means that it
is possible that the child arrives at zipkin before the parent does, but
that's perfectly fine.

**Comment by toaler** [comment] 2016-11-12 16:07
Thanks Adrian, I would expect what you're saying as well.

See the simple test program [1] which creates the parent span with two child span (both local).  If I don't explicitly flush between creating the parent and the second and the second and third span, the first two span's don't appear to make it to the Zipkin server.

Maybe I've doing something wrong.  Happy to know either way.

[1] - https://gist.github.com/toaler/d946d5ee8c055ae979ceeafd63da9b15

**Comment by IainHull** [comment] 2017-04-26 08:28
@toaler Did you ever figure this out? 

I am seeing similar issues with the reporter. Normally the spans are reported correctly. But pushing spans from a short running process like a unit test is not working properly.
* It works when I debug it (due to the extra time taken to step through the code)
* It does not work when I add sleeps to the beginning and of the process (included before and after the last flush)
* It does work when I add sleeps creating sub-spans.

Any light you can shed would be great.

**Comment by adriancole** [comment] 2017-04-26 08:45
@IainHull are you closing the reporter as a teardown in your unit test?

**Comment by IainHull** [comment] 2017-04-26 20:11
Doh!!! Yes you are right I was flushing it but not closing it.

Thanks a million for you help.

**Comment by adriancole** [comment] 2017-04-27 01:23
No problemo!

**Comment by jorgheymans** [comment] 2020-06-12 06:51
Question answered, thanks !

**Closed by jorgheymans** 2020-06-12 06:51 UTC
