### ISSUE TITLE
Sometimes I see "Empty POST body" reported by Zipkin server

### ISSUE THREAD

**Issue by timothybasanov** [openzipkin/zipkin-reporter-java#138] opened 2019-04-15 20:04 UTC
I'm using latest Zipkin 12.5.8, Brave 5.6.2 and zipkin-sender-okhttp3 2.8.1.
Rarely I see this exception on Zipkin side:
```
12:13:36.304 [armeria-common-worker-epoll-4-26] WARN  c.l.a.i.a.AnnotatedHttpService - [id: 0x12fdbdfd, L: R:][h1c://hostname:9411/api/v2/spans#POST] Exception raised by method 'uploadSpans' in 'ZipkinHttpC
ollector':
java.lang.IllegalArgumentException: Empty POST body
        at zipkin2.server.internal.UnzippingBytesRequestConverter.convertRequest(ZipkinHttpCollector.java:161) ~[zipkin-server-2.1
2.8.jar:na]
```

I do not have a reproducible scenario and can not attach a debugger to the Zipkin or Brave  instances that generate that exception.

**Comment by devinsba** [comment] 2019-04-15 20:34
My initial digging didn't find anything in `AsyncReporter` that would cause this. I came up with 2 possibilities:

1. `AsyncReporter.flush()` is being called manually causing a race condition sometimes, causing an empty `List<byte[]>` to be given to the Sender
2. A bug in the encoding size calculation is causing a span that should fit to not fit once the encoding actually happens, causing an empty `List<byte[]>` to be given to the Sender, this would only happen with a single large span being in the buffer

Neither of these seem likely, as I don't think in either case the request body would be completely empty, I don't believe any of the encodings would result in a 0 byte message

**Comment by timothybasanov** [comment] 2019-04-15 20:54
ok. Let’s close this ticket with non-repro. 
If I’d get more specific info I’ll reopen this ticket. 
At least this would be a place some can find if they would have a similar issue in the future

**Comment by adriancole** [comment] 2019-04-16 04:39
ps empty body here would be "" not "[]", so if this was json it would be weird for sure

the reason it throws is because it is a bug to POST empty messages (it skews things like spans per message etc). Maybe throwing could be considered too harsh? cc @openzipkin/core

**Comment by shakuzen** [comment] 2019-04-18 05:07
> Also, if empty request is not valid, may be detect and throw exception on a client side?

Assuming the server is returning an error, it should be in the client metrics, I believe. As for logging, perhaps at DEBUG or TRACE, but probably don't want to be too verbose about logging this.

> Maybe throwing could be considered too harsh?

I agree Zipkin Server throwing and consequently logging this for client exceptions by default is not ideal.

**Comment by adriancole** [comment] 2019-04-25 23:31
I just saw another issue about empty body. For remediation, first I'll fix the server/codec to address it. Next, we can try to pin down how empty is getting through, which is likely here as this was reported in another unrelated sender here: https://github.com/apache/skywalking/issues/2525

note (I've not confirmed that https://github.com/apache/skywalking/issues/2525 is about empty body, but it is suspicious of that.. I will verify soon)

**Comment by adriancole** [comment] 2019-04-26 04:12
fyi I think the skywalking thing is unrelated

**Comment by adriancole** [comment] 2019-04-26 04:47
https://github.com/apache/incubator-zipkin/pull/2538 fixes this

**Comment by adriancole** [comment] 2019-07-04 11:47
also fixed in brave

**Closed by adriancole** 2019-07-04 11:47 UTC
